// ─────────────────────────────────────────────────────────────────────
// ARCHIVO GENERADO — NO EDITAR A MANO.
// Fuente: TIS-F0124 - Código de Defectos (S).xlsx
// Regenerar: python3 tools/gen-catalog.py <ruta-al-xlsx>
// ─────────────────────────────────────────────────────────────────────

export const TIS_F0124_FORM  = 'TIS-F0124';
export const TIS_F0124_REV   = 9;
export const TIS_F0124_FECHA = '2024-09-17';
export const TIS_F0124_SELLO = 'TIS-F0124 Rev.9 (2024-09-17)';

// ── ELEMENTOS (columna A/B del documento) ──────────────────────────
export const ELEMENTOS = [
  { code: 'AI', nombre: 'Aislante', clase: 'ELEC', buscar: 'ai aislante' },
  { code: 'AM', nombre: 'Amarre', clase: 'MEC', buscar: 'am amarre' },
  { code: 'AR', nombre: 'Arnés', clase: 'MEC', buscar: 'ar arnes' },
  { code: 'ARA', nombre: 'Arandela', clase: 'MEC', buscar: 'ara arandela' },
  { code: 'BC', nombre: 'Barra de corto circuito', clase: 'ELEC', buscar: 'bc barra de corto circuito' },
  { code: 'BA', nombre: 'Base', clase: 'MEC', buscar: 'ba base' },
  { code: 'BO', nombre: 'Bota', clase: 'MEC', buscar: 'bo bota' },
  { code: 'BR', nombre: 'Brocha', clase: 'PROC', buscar: 'br brocha' },
  { code: 'BU', nombre: 'Bumper', clase: 'MEC', buscar: 'bu bumper' },
  { code: 'CA', nombre: 'Cable', clase: 'ELEC', buscar: 'ca cable' },
  { code: 'CAM', nombre: 'Campana', clase: 'MEC', buscar: 'cam campana' },
  { code: 'CAN', nombre: 'Canaleta', clase: 'MEC', buscar: 'can canaleta' },
  { code: 'CM', nombre: 'Candado Primario', clase: 'ELEC', buscar: 'cm candado primario' },
  { code: 'CS', nombre: 'Candado Secundario', clase: 'ELEC', buscar: 'cs candado secundario' },
  { code: 'CV', nombre: 'Cavidad', clase: 'ELEC', buscar: 'cv cavidad' },
  { code: 'CO', nombre: 'Clip Corbata', clase: 'MEC', buscar: 'co clip corbata' },
  { code: 'CR', nombre: 'Clip Encintado', clase: 'MEC', buscar: 'cr clip encintado' },
  { code: 'CC', nombre: 'Clip del Conector', clase: 'MEC', buscar: 'cc clip del conector' },
  { code: 'CB', nombre: 'Código de Barras', clase: 'IDENT', buscar: 'cb codigo de barras' },
  { code: 'CI', nombre: 'Conector del Inflador', clase: 'ELEC', buscar: 'ci conector del inflador' },
  { code: 'CP', nombre: 'Conector Principal', clase: 'ELEC', buscar: 'cp conector principal' },
  { code: 'CN', nombre: 'Continuidad', clase: 'ELEC', buscar: 'cn continuidad' },
  { code: 'CL', nombre: 'Coupler', clase: 'ELEC', buscar: 'cl coupler' },
  { code: 'CPA', nombre: 'CPA', clase: 'ELEC', buscar: 'cpa cpa' },
  { code: 'DE', nombre: 'Desforre', clase: 'ELEC', buscar: 'de desforre' },
  { code: 'EM', nombre: 'Empalme', clase: 'ELEC', buscar: 'em empalme' },
  { code: 'EQ', nombre: 'Equipo', clase: 'PROC', buscar: 'eq equipo' },
  { code: 'EN', nombre: 'Encintado / Cinta', clase: 'PROT', buscar: 'en encintado / cinta' },
  { code: 'EST', nombre: 'Estaño', clase: 'ELEC', buscar: 'est estano' },
  { code: 'ET', nombre: 'Etiqueta (caja)', clase: 'IDENT', buscar: 'et etiqueta (caja)' },
  { code: 'FE', nombre: 'Ferrita', clase: 'ELEC', buscar: 'fe ferrita' },
  { code: 'HI', nombre: 'Hilos', clase: 'ELEC', buscar: 'hi hilos' },
  { code: 'LT', nombre: 'Lengüeta de la Terminal', clase: 'ELEC', buscar: 'lt lengueta de la terminal' },
  { code: 'MT', nombre: 'Marca de Tester', clase: 'IDENT', buscar: 'mt marca de tester' },
  { code: 'MU', nombre: 'Muestras', clase: 'PROC', buscar: 'mu muestras' },
  { code: 'PS', nombre: 'Placa Metálica del Switch', clase: 'ELEC', buscar: 'ps placa metalica del switch' },
  { code: 'PC', nombre: 'Prensado del Cable', clase: 'ELEC', buscar: 'pc prensado del cable' },
  { code: 'PA', nombre: 'Prensado del Aislante', clase: 'ELEC', buscar: 'pa prensado del aislante' },
  { code: 'RO', nombre: 'Rondana', clase: 'MEC', buscar: 'ro rondana' },
  { code: 'REM', nombre: 'Remache', clase: 'MEC', buscar: 'rem remache' },
  { code: 'RES', nombre: 'Resorte', clase: 'ELEC', buscar: 'res resorte' },
  { code: 'SE', nombre: 'Sello', clase: 'MEC', buscar: 'se sello' },
  { code: 'SC', nombre: 'Sobrante de corbata', clase: 'PROT', buscar: 'sc sobrante de corbata' },
  { code: 'SO', nombre: 'Soldadura', clase: 'ELEC', buscar: 'so soldadura' },
  { code: 'SW', nombre: 'Switch', clase: 'ELEC', buscar: 'sw switch' },
  { code: 'TA', nombre: 'Tapa / Cubierta', clase: 'MEC', buscar: 'ta tapa / cubierta' },
  { code: 'TE', nombre: 'Terminal', clase: 'ELEC', buscar: 'te terminal' },
  { code: 'TC', nombre: 'Tubo Corrugado', clase: 'PROT', buscar: 'tc tubo corrugado' },
  { code: 'TO', nombre: 'Tornillo', clase: 'MEC', buscar: 'to tornillo' },
  { code: 'TP', nombre: 'Tubo PVC', clase: 'PROT', buscar: 'tp tubo pvc' },
  { code: 'TR', nombre: 'Tubo Reductible', clase: 'PROT', buscar: 'tr tubo reductible' },
  { code: 'TT', nombre: 'Tubo de Tela', clase: 'PROT', buscar: 'tt tubo de tela' },
  { code: 'VE', nombre: 'Ventana', clase: 'MEC', buscar: 've ventana' },
  { code: 'RA', nombre: 'Ramal', clase: 'MEC', buscar: 'ra ramal' },
  { code: 'CE', nombre: 'Marca de Certificacion', clase: 'IDENT', buscar: 'ce marca de certificacion' },
  { code: 'TU', nombre: 'Tuerca', clase: 'MEC', buscar: 'tu tuerca' },
  { code: 'BT', nombre: 'Bloque de Terminales (Block Terminal)', clase: 'ELEC', buscar: 'bt bloque de terminales (block terminal)' },
  { code: 'DI', nombre: 'Dimencion', clase: 'MEC', buscar: 'di dimencion' },
  { code: 'RE', nombre: 'Rebaba', clase: 'MEC', buscar: 're rebaba' },
  { code: 'AL', nombre: 'Ala de la Terminal', clase: 'ELEC', buscar: 'al ala de la terminal' },
  { code: 'EE', nombre: 'Encintado de Esponja', clase: 'PROT', buscar: 'ee encintado de esponja' },
  { code: 'ES', nombre: 'Estompiado', clase: 'ELEC', buscar: 'es estompiado' },
  { code: 'MA', nombre: 'Maquina', clase: 'PROC', buscar: 'ma maquina' },
  { code: 'PI', nombre: 'Pin', clase: 'ELEC', buscar: 'pi pin' },
  { code: 'TS', nombre: 'Terminal Alimentacion Trasera', clase: 'ELEC', buscar: 'ts terminal alimentacion trasera' },
  { code: 'MAN', nombre: 'Manga', clase: 'PROT', buscar: 'man manga' },
  { code: 'GRA', nombre: 'Grapa', clase: 'MEC', buscar: 'gra grapa' },
  { code: 'FLS', nombre: 'Flash', clase: 'MEC', buscar: 'fls flash' },
  { code: 'RAS', nombre: 'Rastreabilidad', clase: 'IDENT', buscar: 'ras rastreabilidad' },
  { code: 'PIG', nombre: 'Pigtail', clase: 'ELEC', buscar: 'pig pigtail' },
  { code: 'ENM', nombre: 'Encintado en manga', clase: 'PROT', buscar: 'enm encintado en manga' },
];

// ── TIPOS DE DEFECTO (columna C/D del documento) ───────────────────
export const TIPOS = [
  { num: 1, nombre: 'Abierto', clase: 'FUNC', buscar: '1 abierto' },
  { num: 2, nombre: 'Adhesivo Expuesto', clase: 'COSM', buscar: '2 adhesivo expuesto' },
  { num: 3, nombre: 'Aplicado Incorrectamente', clase: 'ENS', buscar: '3 aplicado incorrectamente' },
  { num: 4, nombre: 'Resistencia fuera de especificacion', clase: 'FUNC', buscar: '4 resistencia fuera de especificacion' },
  { num: 5, nombre: 'Colapsado', clase: 'FUNC', buscar: '5 colapsado' },
  { num: 6, nombre: 'Bandera', clase: 'COSM', buscar: '6 bandera' },
  { num: 7, nombre: 'Bajo', clase: 'ENS', buscar: '7 bajo' },
  { num: 8, nombre: 'Caido al Piso', clase: 'ENS', buscar: '8 caido al piso' },
  { num: 9, nombre: 'Cerrado', clase: 'ENS', buscar: '9 cerrado' },
  { num: 10, nombre: 'Contaminado', clase: 'ENS', buscar: '10 contaminado' },
  { num: 11, nombre: 'Cortado', clase: 'FUNC', buscar: '11 cortado' },
  { num: 12, nombre: 'Corto', clase: 'FUNC', buscar: '12 corto' },
  { num: 13, nombre: 'Defectuoso de Proveedor', clase: 'FUNC', buscar: '13 defectuoso de proveedor' },
  { num: 14, nombre: 'Dentro del prensado', clase: 'FUNC', buscar: '14 dentro del prensado' },
  { num: 15, nombre: 'Desalineada', clase: 'FUNC', buscar: '15 desalineada' },
  { num: 16, nombre: 'Desfazado', clase: 'ENS', buscar: '16 desfazado' },
  { num: 17, nombre: 'Doble / Duplicado', clase: 'ENS', buscar: '17 doble / duplicado' },
  { num: 18, nombre: 'Exceso', clase: 'COSM', buscar: '18 exceso' },
  { num: 19, nombre: 'Expuesto', clase: 'FUNC', buscar: '19 expuesto' },
  { num: 20, nombre: 'Cortado por maquina sin defecto aparente', clase: 'DISP', buscar: '20 cortado por maquina sin defecto aparente' },
  { num: 21, nombre: 'Falta Calor', clase: 'ENS', buscar: '21 falta calor' },
  { num: 22, nombre: 'Faltante', clase: 'ENS', buscar: '22 faltante' },
  { num: 23, nombre: 'Flojo', clase: 'ENS', buscar: '23 flojo' },
  { num: 24, nombre: 'Fuera de tolerancia', clase: 'ENS', buscar: '24 fuera de tolerancia' },
  { num: 25, nombre: 'Ilegible', clase: 'IDENT', buscar: '25 ilegible' },
  { num: 26, nombre: 'Incorrecto', clase: 'ENS', buscar: '26 incorrecto' },
  { num: 27, nombre: 'Invertido', clase: 'FUNC', buscar: '27 invertido' },
  { num: 28, nombre: 'Jalado', clase: 'FUNC', buscar: '28 jalado' },
  { num: 29, nombre: 'Largo', clase: 'ENS', buscar: '29 largo' },
  { num: 30, nombre: 'Marcado', clase: 'IDENT', buscar: '30 marcado' },
  { num: 31, nombre: 'Menos de dos Vueltas', clase: 'ENS', buscar: '31 menos de dos vueltas' },
  { num: 32, nombre: 'No Asentado Completamente', clase: 'FUNC', buscar: '32 no asentado completamente' },
  { num: 33, nombre: 'Obstruida', clase: 'FUNC', buscar: '33 obstruida' },
  { num: 34, nombre: 'Orientación Incorrecta', clase: 'ENS', buscar: '34 orientacion incorrecta' },
  { num: 35, nombre: 'Perforado', clase: 'FUNC', buscar: '35 perforado' },
  { num: 36, nombre: 'Roto', clase: 'FUNC', buscar: '36 roto' },
  { num: 37, nombre: 'Quebrado', clase: 'FUNC', buscar: '37 quebrado' },
  { num: 38, nombre: 'Quemado', clase: 'FUNC', buscar: '38 quemado' },
  { num: 39, nombre: 'Rebaba', clase: 'COSM', buscar: '39 rebaba' },
  { num: 40, nombre: 'Cantidad fuera del estandar', clase: 'ENS', buscar: '40 cantidad fuera del estandar' },
  { num: 41, nombre: 'Tenso', clase: 'ENS', buscar: '41 tenso' },
  { num: 42, nombre: 'Torcido', clase: 'ENS', buscar: '42 torcido' },
  { num: 43, nombre: 'Desperdiciado por Mantenimiento', clase: 'DISP', buscar: '43 desperdiciado por mantenimiento' },
  { num: 44, nombre: 'Desperdiciado por Proceso', clase: 'DISP', buscar: '44 desperdiciado por proceso' },
  { num: 45, nombre: 'Desperdiciado por Pruebas de Calidad', clase: 'DISP', buscar: '45 desperdiciado por pruebas de calidad' },
  { num: 46, nombre: 'Rechazado por monitor de Prensado', clase: 'FUNC', buscar: '46 rechazado por monitor de prensado' },
  { num: 47, nombre: 'Embarrados', clase: 'FUNC', buscar: '47 embarrados' },
  { num: 48, nombre: 'Girada', clase: 'FUNC', buscar: '48 girada' },
  { num: 49, nombre: 'Enterrado', clase: 'FUNC', buscar: '49 enterrado' },
  { num: 50, nombre: 'Fuera del Prensado', clase: 'FUNC', buscar: '50 fuera del prensado' },
  { num: 51, nombre: 'Fallo por pieza no cargada correctamente en tester', clase: 'DISP', buscar: '51 fallo por pieza no cargada correctamente en tester' },
  { num: 52, nombre: 'Retrabajo (autorizado)', clase: 'DISP', buscar: '52 retrabajo (autorizado)' },
  { num: 53, nombre: 'Muestras de Set Up', clase: 'DISP', buscar: '53 muestras de set up' },
  { num: 54, nombre: 'Desperdiciado por cambios o arranques de ingenieria', clase: 'DISP', buscar: '54 desperdiciado por cambios o arranques de ingenieria' },
  { num: 55, nombre: 'Falta de calibracion', clase: 'ENS', buscar: '55 falta de calibracion' },
  { num: 56, nombre: 'Danada', clase: 'FUNC', buscar: '56 danada' },
  { num: 57, nombre: 'Doblado (Banana)', clase: 'FUNC', buscar: '57 doblado (banana)' },
  { num: 58, nombre: 'Apretado', clase: 'ENS', buscar: '58 apretado' },
  { num: 59, nombre: 'Espiral', clase: 'COSM', buscar: '59 espiral' },
  { num: 60, nombre: 'Fallo', clase: 'FUNC', buscar: '60 fallo' },
  { num: 61, nombre: 'Incompleto', clase: 'ENS', buscar: '61 incompleto' },
  { num: 62, nombre: 'Sobrante', clase: 'COSM', buscar: '62 sobrante' },
  { num: 63, nombre: 'Duplicado', clase: 'ENS', buscar: '63 duplicado' },
  { num: 64, nombre: 'Incorrecta Operación del Operador', clase: 'ENS', buscar: '64 incorrecta operacion del operador' },
  { num: 65, nombre: 'Golpeado', clase: 'ENS', buscar: '65 golpeado' },
  { num: 66, nombre: 'Aplastado', clase: 'FUNC', buscar: '66 aplastado' },
  { num: 67, nombre: 'Mezclado', clase: 'ENS', buscar: '67 mezclado' },
  { num: 68, nombre: 'Mal identificado', clase: 'IDENT', buscar: '68 mal identificado' },
  { num: 69, nombre: 'Fuera del encintado', clase: 'ENS', buscar: '69 fuera del encintado' },
  { num: 70, nombre: 'Mal ruteado', clase: 'ENS', buscar: '70 mal ruteado' },
  { num: 71, nombre: 'Deshilachado', clase: 'COSM', buscar: '71 deshilachado' },
  { num: 72, nombre: 'Curva', clase: 'FUNC', buscar: '72 curva' },
];

// ── SEVERIDAD (hoja Sheet1 del documento) ──────────────────────────
export const SEVERIDADES = {
  'A': 'Problemas electricos (falla funcional del arnes/vehiculo):\n-Falla de prensado (Aislante dentro del prensado, hilos cortados o fuera del prensado, no hilos dentro del prensado, etc).\n-Terminal no asentada/terminal jalada.\n-Terminales desalineadas/dobladas.\nProblemas de identificacion:\n-Barcode ilegible.\n-Falta de barcode.\n-Barcode no corresponde al arnes/NP.',
  'B': 'Problemas de ensamble: \n-Problemas dimensionales (clip, ramales, pvc fuera de tolerancia).\n-Falta de componentes (clip faltante, encintado, candado secundarios faltantes, candandos abiertos,etc).\n-Clip equivocado.',
  'C': 'Problemas de encintado/esteticos:\n-Encintado en bandera, encintado pobre, exceso de cinta. \n-Exceso de corbata en clip. \n-Clip deforme (se puede ensamblar).\n-PVC, corrugado, tubo de calor, mal cortado (sesgado).',
};

// ── Anclajes documentales: ganan sobre la matriz ───────────────────
export const ANCLAJES_DOC = {
  'AI-14': { sev: 'A', cita: 'A · Falla de prensado (aislante dentro del prensado)' },
  'CB-22': { sev: 'A', cita: 'A · Barcode ilegible / falta de barcode / barcode no corresponde al arnés o NP' },
  'CB-25': { sev: 'A', cita: 'A · Barcode ilegible / falta de barcode / barcode no corresponde al arnés o NP' },
  'CB-26': { sev: 'A', cita: 'A · Barcode ilegible / falta de barcode / barcode no corresponde al arnés o NP' },
  'CC-22': { sev: 'B', cita: 'B · Falta de componentes (clip faltante, encintado, candados secundarios faltantes)' },
  'CC-24': { sev: 'B', cita: 'B · Problemas dimensionales (clip, ramales, pvc fuera de tolerancia)' },
  'CC-26': { sev: 'B', cita: 'B · Clip equivocado' },
  'CC-42': { sev: 'C', cita: 'C · Clip deforme (se puede ensamblar)' },
  'CM-1': { sev: 'B', cita: 'B · Falta de componentes (candados abiertos)' },
  'CO-22': { sev: 'B', cita: 'B · Falta de componentes (clip faltante, encintado, candados secundarios faltantes)' },
  'CO-24': { sev: 'B', cita: 'B · Problemas dimensionales (clip, ramales, pvc fuera de tolerancia)' },
  'CO-26': { sev: 'B', cita: 'B · Clip equivocado' },
  'CO-42': { sev: 'C', cita: 'C · Clip deforme (se puede ensamblar)' },
  'CR-22': { sev: 'B', cita: 'B · Falta de componentes (clip faltante, encintado, candados secundarios faltantes)' },
  'CR-24': { sev: 'B', cita: 'B · Problemas dimensionales (clip, ramales, pvc fuera de tolerancia)' },
  'CR-26': { sev: 'B', cita: 'B · Clip equivocado' },
  'CR-42': { sev: 'C', cita: 'C · Clip deforme (se puede ensamblar)' },
  'CS-1': { sev: 'B', cita: 'B · Falta de componentes (candados abiertos)' },
  'CS-22': { sev: 'B', cita: 'B · Falta de componentes (clip faltante, encintado, candados secundarios faltantes)' },
  'DI-24': { sev: 'B', cita: 'B · Problemas dimensionales (clip, ramales, pvc fuera de tolerancia)' },
  'EN-6': { sev: 'C', cita: 'C · Encintado en bandera, encintado pobre, exceso de cinta' },
  'EN-18': { sev: 'C', cita: 'C · Encintado en bandera, encintado pobre, exceso de cinta' },
  'EN-22': { sev: 'B', cita: 'B · Falta de componentes (clip faltante, encintado, candados secundarios faltantes)' },
  'EN-61': { sev: 'C', cita: 'C · Encintado en bandera, encintado pobre, exceso de cinta' },
  'HI-11': { sev: 'A', cita: 'A · Falla de prensado (hilos cortados o fuera del prensado, no hilos dentro del prensado)' },
  'HI-14': { sev: 'A', cita: 'A · Falla de prensado (hilos cortados o fuera del prensado, no hilos dentro del prensado)' },
  'HI-22': { sev: 'A', cita: 'A · Falla de prensado (hilos cortados o fuera del prensado, no hilos dentro del prensado)' },
  'HI-50': { sev: 'A', cita: 'A · Falla de prensado (hilos cortados o fuera del prensado, no hilos dentro del prensado)' },
  'PA-11': { sev: 'A', cita: 'A · Falla de prensado (aislante dentro del prensado, hilos cortados o fuera del prensado, no hilos dentro del prensado)' },
  'PA-14': { sev: 'A', cita: 'A · Falla de prensado (aislante dentro del prensado, hilos cortados o fuera del prensado, no hilos dentro del prensado)' },
  'PA-19': { sev: 'A', cita: 'A · Falla de prensado (aislante dentro del prensado, hilos cortados o fuera del prensado, no hilos dentro del prensado)' },
  'PA-22': { sev: 'A', cita: 'A · Falla de prensado (aislante dentro del prensado, hilos cortados o fuera del prensado, no hilos dentro del prensado)' },
  'PA-32': { sev: 'A', cita: 'A · Falla de prensado (aislante dentro del prensado, hilos cortados o fuera del prensado, no hilos dentro del prensado)' },
  'PA-50': { sev: 'A', cita: 'A · Falla de prensado (aislante dentro del prensado, hilos cortados o fuera del prensado, no hilos dentro del prensado)' },
  'PC-11': { sev: 'A', cita: 'A · Falla de prensado (aislante dentro del prensado, hilos cortados o fuera del prensado, no hilos dentro del prensado)' },
  'PC-14': { sev: 'A', cita: 'A · Falla de prensado (aislante dentro del prensado, hilos cortados o fuera del prensado, no hilos dentro del prensado)' },
  'PC-19': { sev: 'A', cita: 'A · Falla de prensado (aislante dentro del prensado, hilos cortados o fuera del prensado, no hilos dentro del prensado)' },
  'PC-22': { sev: 'A', cita: 'A · Falla de prensado (aislante dentro del prensado, hilos cortados o fuera del prensado, no hilos dentro del prensado)' },
  'PC-32': { sev: 'A', cita: 'A · Falla de prensado (aislante dentro del prensado, hilos cortados o fuera del prensado, no hilos dentro del prensado)' },
  'PC-50': { sev: 'A', cita: 'A · Falla de prensado (aislante dentro del prensado, hilos cortados o fuera del prensado, no hilos dentro del prensado)' },
  'RA-24': { sev: 'B', cita: 'B · Problemas dimensionales (clip, ramales, pvc fuera de tolerancia)' },
  'SC-18': { sev: 'C', cita: 'C · Exceso de corbata en clip' },
  'SE-22': { sev: 'B', cita: 'B · Falta de componentes (clip faltante, encintado, candados secundarios faltantes)' },
  'TC-11': { sev: 'C', cita: 'C · PVC, corrugado, tubo de calor, mal cortado (sesgado)' },
  'TC-16': { sev: 'C', cita: 'C · PVC, corrugado, tubo de calor, mal cortado (sesgado)' },
  'TE-15': { sev: 'A', cita: 'A · Terminales desalineadas / dobladas' },
  'TE-28': { sev: 'A', cita: 'A · Terminal no asentada / terminal jalada' },
  'TE-32': { sev: 'A', cita: 'A · Terminal no asentada / terminal jalada' },
  'TE-57': { sev: 'A', cita: 'A · Terminales desalineadas / dobladas' },
  'TP-11': { sev: 'C', cita: 'C · PVC, corrugado, tubo de calor, mal cortado (sesgado)' },
  'TP-16': { sev: 'C', cita: 'C · PVC, corrugado, tubo de calor, mal cortado (sesgado)' },
  'TP-24': { sev: 'B', cita: 'B · Problemas dimensionales (clip, ramales, pvc fuera de tolerancia)' },
  'TR-11': { sev: 'C', cita: 'C · PVC, corrugado, tubo de calor, mal cortado (sesgado)' },
  'TR-16': { sev: 'C', cita: 'C · PVC, corrugado, tubo de calor, mal cortado (sesgado)' },
};

// ── Matriz clase-elemento × clase-tipo ─────────────────────────────
export const MATRIZ_SEVERIDAD = {
  ELEC: { FUNC: 'A', IDENT: 'B', ENS: 'B', COSM: 'C' },
  IDENT: { FUNC: 'A', IDENT: 'A', ENS: 'B', COSM: 'C' },
  MEC: { FUNC: 'B', IDENT: 'B', ENS: 'B', COSM: 'C' },
  PROT: { FUNC: 'C', IDENT: 'C', ENS: 'C', COSM: 'C' },
  PROC: { FUNC: 'B', IDENT: 'B', ENS: 'B', COSM: 'C' },
};

export const SEVERIDAD_DEFAULT = 'B';

// ── Migración del catálogo legado ──────────────────────────────────
export const LEGADO_DETERMINISTA = {
  'Terminal no insertada (Push-back)': { el: 'TE', tipo: 32 },
  'Cables invertidos (Miswire)': { el: 'CA', tipo: 27 },
  'Circuito abierto / Sin continuidad': { el: 'CN', tipo: 1 },
  'Cortocircuito': { el: 'CN', tipo: 12 },
  'Terminal dañada / Deformada': { el: 'TE', tipo: 56 },
};

export const LEGADO_AMBIGUO = {
  'Daño en aislamiento / Cobre expuesto': 'Dos modos distintos: AI-56 (aislante dañado) vs HI-19 (hilos expuestos)',
  'Falta de componente (Clip, Sello, TPA)': 'La etiqueta nombra tres elementos candidatos: CO/CR/CC, SE y CPA',
  'Conector dañado / Roto': 'Tipo determinado (36) pero elemento no: CP, CI o CL',
  'Ruteo incorrecto / Longitud': 'AR-70 (mal ruteado) vs DI-24 (fuera de tolerancia)',
  'Encintado defectuoso / Faltante': 'EN-61 (incompleto) vs EN-22 (faltante)',
};

